### ISSUE TITLE
Create a dipole fitting GUI that is better than XFit

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#11977]
### Describe the new feature or enhancement

Starting an issue to discuss our dream dipole fitting interface. MEGIN's Xfit program has reigned supreme for what seems like forever, but that doesn't mean it's perfect.

Use cases for Xfit (feel free to add your own). Indented ones are things we can do that Xfit can not:

### 3D Viewer
 - [x] View magnetic field patterns for evokeds. Scroll through time. (#11942)
 - [x] View head-in-helmet alignment (`plot_alignment` and `Brain.add_head`)
   - [x] Plot the brain and reconstructed head surface (verifying MRI alignment) 
   - [x] Plot MNE source activity to guide dipole modelling
 - [ ] See magnetic field patterns produced by selected subset of sensors only

### Evoked topo plot
 - [x] View sensor-level evokeds in topo form (`plot_evoked_topo`)
 - [x] Use lasso select instead of rectangular box (#12071)
 - [ ] Quickly adjust `ylim` for sensor-level evokeds view (#11892)
 - [ ] Quickly toggle mag/grad/eeg for sensor-level evokeds view
 - [ ] Overlay signal explained by fitted dipoles on top of the sensor-level signals
   - [ ] Do this for multiple evokeds (e.g. multiple conditions) 

### Dipole fitting algorithm
 - [x] When computing dipole timecourses, select between single-dipole or multi-dipole modeling
 - [x] Select whether fitted dipoles are allowed to rotate in time or not
 - [x] Use freesurfer-based BEM model
 - [x] Use sphere BEM model
 - [x] Select noise-cov or use "standard" one
 - [ ] Compute signal explained by fitted dipoles on top of the sensor-level signals

### Dipole fitting UI features
- [x] Fit dipole with the click of a button
- [x] See dipole projected on the helmet as an arrow
- [x] See dipole as an arrow in the brain
- [x] See dipole timecourse
  - [ ] See dipole timecourse for multiple evokeds (e.g. multiple conditions) 
- [x] Select subset of sensors and fit dipole with only those sensors
- [x] Fit more than one dipole (https://mne.tools/stable/auto_examples/inverse/multi_dipole_model.html)
- [x] Save fitted dipoles to file
  - [x] Load fitted dipoles from file
- [x] See percentage of signal variance explained by fitted dipoles
- [x] Turn dipoles on and off
  - [x] Delete dipoles from the UI
 - [ ] Toggle removing computed signal from the evokeds (Xfit called this the "complement")

### Describe your proposed implementation

Use UI event system to tie together existing plotting functions. Enhance existing plotting functions to allow for more interactivity. Finally, create complete GUI with all these pieces.

### Describe possible alternatives

Stick with Xfit. Possibly the GUI could be a separate package (`mne-xfit`?)

**Comment by larsoner** [comment]
We should consider also how many of these we can fix at the same time (maybe zero but hopefully more than that):

- https://github.com/mne-tools/mne-python/issues/2995
- https://github.com/mne-tools/mne-python/issues/4655
- https://github.com/mne-tools/mne-python/issues/11376

**Comment by larsoner** [comment]
@wmvanvliet clearing the milestone on this one but feel free to put it to 1.9 if you think you'll have time in the next release cycle
