### ISSUE TITLE
GSOC on VIZ TODO list

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#2213]
In a discussion with @dengemann and @mainakjas, we decided to make a list of things to do over this GSOC. Feel free to add items to the list. Preferably stuff about the vizualization, since that's my field for this GSOC.

**Comment by teonlamont** [comment]
These are html visualizations/interactions with MNE-Report that could be improved upon:

MNE-Report toggle button https://github.com/mne-tools/mne-python/issues/1996
MNE-Report html issue https://github.com/mne-tools/mne-python/issues/2212

**Comment by agramfort** [comment]
time frequency interactive viz e.g. select region of tf plane and get the
associated topography (see how fieldtrip does it).

maybe interactive selection of bad ICA components (via topo or time courses)

**Comment by mainakjas** [comment]
@teonlamont I can take care of those two issues so that @jaeilepp can focus on core functionality.

**Comment by mainakjas** [comment]
filing one idea we had discussed with @dengemann : topoplot with sliders (for different time points) in mne-report (like the bem plot). Good to visualize evolution of evoked response

**Comment by mainakjas** [comment]
... also interactive picking of channels from a plotted layout. @teonlamont can give a demo maybe how he uses it.

**Comment by teonlamont** [comment]
also, it would be nice if we could have a standalone viewer of Montage/DigMontage class. it's essentially already implemented in kit2fiff gui. it would just need the removal of the KIT input file. The reason it would be useful to have it is that if you are interested in your `dev_head_t`, you can then visualize the headshape info and the device hpi coil points. there are often cases where hpi coils fall off and the `dev_head_t` would be affected by it.

**Comment by teonlamont** [comment]
and @mainakjas i'm looking forward to your pr's ;)

**Comment by kingjr** [comment]
> filing one idea we had discussed with @dengemann : topoplot with sliders (for different time points) in mne-report (like the bem plot). Good to visualize evolution of evoked response

What I sometimes do is making animated gif. They're easy to email or put them in powerpoints slides. It'd be great to have this within the package, although I guess it's a bit vintage.

**Comment by dengemann** [comment]
> also, it would be nice if we could have a standalone viewer of Montage/DigMontage class. it's essentially already implemented in kit2fiff gui. it would just need the removal of the KIT input file. The reason it would be useful to have it is that if you are interested in your dev_head_t, you can then visualize the headshape info and the device hpi coil points. there are often cases where hpi coils fall off and the dev_head_t would be affected by it.

maybe not directly related to Jaakko's GSOC, no?

**Comment by dengemann** [comment]
I'll list the points in a more  structured way:

For existing functions:
- [ ] add scale + unit information on demand to browser plots
- [ ] add option to hide channel names for views with more many channels, e.g. > 100. Maybe auto-hide
- [ ] infobox with more precise control options, e.g. add 40 channels, add 22 epochs, etc.

Next/Maybe:
- [ ] scrollable topomps in matplotlib / report
- [ ] interactive TFR plotting
- [ ] interactive ICA selection

**Comment by dengemann** [comment]
To keep the discussion compact, please edit my post above to add items.

**Comment by teonlamont** [comment]
+1 on the scrollable plots/slider. it should be general so that you can take any series of images and turn them into a slider. currently dealing with ROC curves over time and it would be great to have a way to consolidating all the plots into one figure.

**Comment by dengemann** [comment]
updated todo @jaeilepp

**Comment by jaeilepp** [comment]
I can't seem to update the checkboxes on @dengemann comment.
- [ ] add scale + unit information on demand to browser plots
- [ ] add option to hide channel names for views with more many channels, e.g. > 100. Maybe auto-hide
- [ ] infobox with more precise control options, e.g. add 40 channels, add 22 epochs, etc.
- [ ] make sure all interactive options can be initialized from the function call
- [ ] option to turn off event start line
- [ ] evoked.plot_topo cf #2240 (added by mainak)

Next/Maybe:
- [ ] scrollable topomps in matplotlib / report
- [ ] interactive TFR plotting
- [ ] interactive ICA selection

**Comment by jaeilepp** [comment]
> make sure all interactive options can be initialized from the function call

Do you mean that for example butterfly plot should be operated with a boolean mask (butterfly=True)?

**Comment by dengemann** [comment]
Yes or view/mode='butterfly' this would also help avoid the trellis param

**Comment by Eric89GXL** [comment]
GSoC is over now, so I'm closing. But it's nice to see a mostly cleared long checklist above @jaeilepp :)
