### ISSUE TITLE
Memory consuming functions

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#2864]
I ran memory profiler on our examples to track down memory consuming functions. I thought that I'd share the results here if someone else wants to look at it. The examples listed here have a peak consumption of over 1 GiB.

* [x] ~~datasets/plot_brainstorm_data.py~~ (#2977)
* [x] ~~datasets/plot_spm_faces_dataset.py~~ (#2977)
* [x] ~~decoding/plot_decoding_spatio_temporal_source.py~~ (#2977)
* [x] ~~decoding/plot_decoding_time_generalization.py~~ (#2977)
* [x] ~~inverse/plot_covariance_whitening_dspm.py~~ (#2977)
* [x] ~~inverse/plot_tf_lcmv.py~~ (#2977)
* [x] ~~visualization/plot_meg_eeg_fields_3d.py~~ (#2977)
* [x] ~~forward/plot_source_space_morphing.py~~ (#2972)
* [x] ~~preprocessing/plot_resample.py~~ (#2972)
* [x] ~~simulation/plot_simulate_raw_data.py~~ (#2972)
* [x] ~~stats/plot_linear_regression_raw.py~~ (#2972)
* [x] ~~time_frequency/plot_compute_raw_data_spectrum.py~~ (#2972)
* [x] ~~time_frequency/plot_epochs_spectra.py~~ (#2972)

**Comment by agramfort** [comment]
do you have the exact peak value for all of them?

**Comment by jaeilepp** [comment]
Not right now, but I can check.
