### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#3985]
Here I'm going to list some of the topics that people have mentioned below, as well as some that I've noticed myself. This pulls in outstanding (aka, unchecked) points within #3082 as well.

[link to the dev docs here](http://martinos.org/mne/dev/auto_examples/index.html)
[link to docs mega-issue here](https://github.com/mne-tools/mne-python/issues/1495)
maybe we wanna merge this thread in with the other mega-doc issue, but for now I'll work from here unless folks say otherwise. I think there's value in not having that issue get too gigantic.

# General
- [x] Make it more clear the difference between manual and the tutorials. What is the conceptual difference between, e.g. [this manual item](http://martinos.org/mne/dev/manual/time_frequency.html) and [this tutorail item](http://martinos.org/mne/dev/auto_tutorials/plot_sensors_time_frequency.html) 
- [x] The dev docs are still matplotlib 1.X, will they be ported to 2.X at some point? The plots look prettier there :)
- [x] The CSS of the website causes it to fill the width of the screen at all times. For some things (e.g. the tutorials / examples) I feel like it might be easier to read the material if the CSS stuck with a particular width (e.g. the width of jupyter notebooks)

# Little things
- [x] [the RSA example](http://martinos.org/mne/dev/auto_examples/decoding/decoding_rsa.html#sphx-glr-auto-examples-decoding-decoding-rsa-py) doesn't seem to be running
- [ ] ~~[this durface decimation example](http://martinos.org/mne/dev/auto_examples/forward/plot_decimate_head_surface.html#sphx-glr-auto-examples-forward-plot-decimate-head-surface-py) isn't plotting anything because all the mayavi lines are commented out~~ *example no longer exists*
- [x] [the event reading example](http://martinos.org/mne/dev/auto_examples/io/read_events.html#sphx-glr-auto-examples-io-read-events-py) doesn't have a plot, but we could easily use the `plot_events` function.
- [ ] ~~the description in [this example](http://martinos.org/mne/dev/auto_examples/realtime/ftclient_rt_compute_psd.html#sphx-glr-auto-examples-realtime-ftclient-rt-compute-psd-py) references a python file, but instead should link to the example for this file in the gallery.~~ *realtime is its own module now*
- [x] the [report example](http://martinos.org/mne/dev/auto_examples/visualization/make_report.html#sphx-glr-auto-examples-visualization-make-report-py) could show a sample image of what a report looks like.
- [ ] ~~The [clickable image](http://martinos.org/mne/dev/auto_examples/visualization/plot_clickable_image.html#sphx-glr-auto-examples-visualization-plot-clickable-image-py) example could show or reference the 3-D snapshotting functionality demoed [here](http://martinos.org/mne/dev/auto_tutorials/plot_ecog.html)~~ *example no longer exists*
- [x] Clarify that it's important to baseline epochs before computing noise covariance in one of the examples or in the manual *done in auto_tutorials/source-modeling/plot_compute_covariance.html*
- [x] Elaborate on use of the lambda2 parameter in `apply_inverse`. E.g., why is it set to 1/2**3 most of the time? *this is now tolerably well explained in the [inverse modeling section](https://mne.tools/dev/auto_tutorials/intro/plot_10_overview.html?highlight=regularization#inverse-modeling) of the overview tutorial. Though it doesn't say why we assume SNR of 3; at least it explains what lambda2 represents and users can infer how to sensibly tweak it.*

# Medium things
- [ ] create a workflow diagram for a processing pipeline (see #3669 for example) 
- [ ] Add an example of how to grand average source data. (there seems to be a function for evoked and TF data but not for source). Maybe by morphing them creating a multidimensional matrix np.array and doing the average manually.
- [ ] Improve documentation about signal-to-noise estimation, see #1857
- [ ] A better tutorial for `make_bem_watershed`. And what to do with the error that one surface intersects with another. (sort of a freesurfer problem)
- [ ] Add a tutorial for Granger analysis using nipy (#3548)
- [ ] Add a tutorial on co-registration (#3358)
- [ ] Document risks of whitening with multiple SSS runs (#1902)

# Large things
- [ ] Documenting the connectivity module (#2847)

**Comment by kingjr** [comment]
I think we should merge the 'manual' and the 'tutorials'.

**Comment by Eric89GXL** [comment]
Good targets would be:

* @choldgraf and @kingjr ideas for [updating the workflow](https://github.com/mne-tools/mne-python/issues/3669), especially if someone wants to make a client-side rendered workflow image :)
* @teonbrooks [small issues](#3082) you hit
* @dengemann [SNR doc](#1857)
* @dengemann [connectivity doc](#2847)
* and there is of course the [doc mega-issue](#1495)

**Comment by Eric89GXL** [comment]
And:

* @christianbrodbeck [tutorial on coreg](#3358)

**Comment by choldgraf** [comment]
@Eric89GXL it seems like most of those links just redirect back to this issue?

Those are great suggestions though. If we can get an idea for prioritizing these in some way (e.g. I think a tutorial on coregistration would be useful, especially if there could eventually be support for doing ecog coregistration using a CT scan or something)

**Comment by claire-braboszcz** [comment]
I've seen on [Project](https://github.com/mne-tools/mne-python/projects/1) that @kingjr was thinking of writing a tutorial on time-frequency decoding. I'd be very interested in such a tutorial that would complement nicely [the current documentation](http://martinos.org/mne/dev/manual/decoding.html).

**Comment by Eric89GXL** [comment]
@choldgraf fixed all the links.

Are people working on any of these this week?

**Comment by choldgraf** [comment]
I'm gonna take a pass through this and try to organize a little bit today...just been slow on doing it since I had to get the docathon up and running first :)  I think @teonbrooks is going to help out as well

**Comment by choldgraf** [comment]
I'm looking through some of these issues etc now, and it's a little unclear to me what is the difference between "tutorials" and the "guide". Can somebody give me the high-level view of why these are two different things? Is the guide meant to be comprehensive and very MNE-specific, whereas tutorials are more conceptual in nature?

**Comment by choldgraf** [comment]
E.g., what would be the difference between this page:

http://martinos.org/mne/stable/manual/time_frequency.html

and this page:

http://martinos.org/mne/stable/auto_tutorials/plot_sensors_time_frequency.html

**Comment by agramfort** [comment]
hum... maybe http://martinos.org/mne/stable/manual/time_frequency.html should
not be there.

the "idea" is to have the manual more conceptual closer to the explanation
of the method
in a book or paper and to say when you should or should not use it. But
maybe it's too ambitious...

the tutorial are more really how to do things with MNE.

most of the manual content comes from the pdf doc of the MNE-C code.

**Comment by choldgraf** [comment]
Maybe it'd be worth having language on the landing page that describes this? I remember when I was starting with MNE it was unclear which of the two I should be reading. I actually really like the idea of having more high-level concepts-based materials in the repo, since a lot of students learn by looking through project docs these days.

I think a challenge is that we'd need to be fairly vigilant about what belongs in tutorials vs. manual. For example, in tutorials there is [this general example on filtering](http://martinos.org/mne/stable/auto_tutorials/plot_background_filtering.html). If the manual is supposed to be more "concepts based" then this should really be in there. My assumption is that most users will get a feeling for what a section of the website covers by clicking a random link and seeing what kind of information is in there.

**Comment by choldgraf** [comment]
And for a converse example, [this manual page on epochs etc](http://martinos.org/mne/stable/manual/cookbook.html#epoching-and-evoked-data) feels much more like a "how to use MNE" kind of document than a "general concepts" kind of document.

Maybe worth spending an hour at the meeting in NYC to chat about best way to organize / present this information? I think there's a lot of great info in there - wanna make sure that people will find it!

**Comment by kingjr** [comment]
+1

**Comment by agramfort** [comment]
+ np.info['int64'].max

Alex

**Comment by choldgraf** [comment]
sounds like all(opinion > 0 for opinion in thread_opinions) == True

I'll add to the project board

**Comment by prateekj117** [comment]
@larsoner We should change the installation command for sphinx-autobuild and doc8 in the documentation from `conda install sphinx-autobuild doc8` to `conda install -c conda-forge sphinx-autobuild doc8` in case someone does not have conda-forge added to their channel list.

Rather than opening a separate issue, I think it would be more appropriate to add it here.

**Comment by drammock** [comment]
@prateekj117 thanks for pointing that out, see #7050

**Comment by drammock** [comment]
All of the remaining unchecked boxes in this todo-list have been added to #6794. Closing.

**Comment by choldgraf** [comment]
amazing!
