### ISSUE TITLE
DOC, TODO: advanced git page?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6266]
I'd been hoping we could avoid it and let the rest of the internet handle advanced git advice, but based on conversations in #6254, it seems like a troubleshooting / advanced git page might be wanted (at least by some)?

- [ ] when, how, and why to rebase
- [ ] tips like `git push -u`
- [ ] `git commit --amend` and `git push --force`
- [ ] `git stash`

@jeythekey @massich @larsoner @mmagnuski
