### ISSUE TITLE
Digitization progress

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#6461]
This issue is to keep track of the remaining Digitization PRs. It reflects a conversation with @larsoner.

TODO (each item will be a separate PR):

- [x] Add move all `montage` use to Raw and Epochs readers that have `montage` argument to call only the following at the end of their `__init__`, not used anywhere else (#6462):
   ```
   if montage is not None:
       self.set_montage(montage)
   ```

- [ ] Deprecate `montage` argument in all readers that support `montage` arguments (#6534)

	- [ ] Make we have a test like sure https://github.com/mne-tools/mne-python/issues/6461#issuecomment-503584614 
		```py
		def test_montage():
	    	raw_montage = read_raw_*(fname, montage=my_montage)
		    raw_none = read_raw_*(fname, montage=None)
		    raw_none.set_montage(montage)
		    assert object_diff(raw_none.info['chs'], raw_montage.info['chs'])
	    	assert object_diff(raw_none.info['dig'], raw_montage.info['dig'])
		```

- [ ] ~Replicate montage and digmontage usecases with `Digitization`~ This no longer applies. We kept `DigMontage`, remove `Montage` and make `digitization` private.
	- [x] Refactor `DigMontage` to use `Digitization` + `ch_names` as representation (+ deprecate things that we no longer want to support) (#6639)
	- [x] Make `digitization` module private `_digitization` (#6700)
  - [ ] Fix `DigMontage.save` (saves `dig` but not `ch_names`)
  - [x] Fix `DigMontage()` without parmeters.
  - [ ] Refactor `DigMontage` tests. All that we did not change in #6639 because we only wanted to touch code logic not test logic.
  - [ ] `set_montage` takes only `DigMontage` not `Montage`
  - [ ] Some refactor of `mne/_digitization`. We have all `_make_dig_{kit, artemist, bti}` that overlap with `DigMontage`.
  - [ ] deprecate `read_dig_montage` in favor of `read_dig_montage_FOO` or `make_dig_montage(np.arrays..)`. **No transforms allowed**.
  - [x] deprecate `DigMontage.dev_head_t` in favor of:
    - Storing the 2 versionsof the HPI points in the `DigMontage.dig`: one in `FIFFV_COORD_HEAD` and the other in `FIFFV_COORD_MEG`.
       When you want `dev_head_t`, call `DigMontage.get_dev_head_t()` and it will compute it from these directly.
    - a free function returning a proper transformation: `def compute_dev_head_t(dig: Digitization) -> Transform:`
  - [x] rename `elp`, `hpi` in favor of the new names (`hpi`, `hpi_dev`) in the internal calls. (I'm not sure this will be needed. We'll see)
  - [ ] `DigMontage.transform_to_head()` (not fully clear but it will get more clear when addressing the others). Things that could require:
    - a free function like: `def get_fiducials(dig: Digitization) -> Fiducials:` (`Fiducials` is a `Bunch` with `nasion`, `lpa`, `rpa` or similar, named tuple whatever.)
    - do all points need to be in 'head' or only some of them?
    - does it need to be a method? (probably yes)

- [ ] remove fit_match_points outside of coreg.

- [ ] move `read_dig_XXXX` to `mne/io/`

- [ ] ~Add `plot()` to `Digitization` class #6412. 3D plot with each dig point, maybe symbol based on coordinate frame (sphere=head, cube=meg, ... ?) and color based on type (eeg, extra, hpi, we have colors for these in `defaults.py` or `plot_alignment` somewhere)~ Fix the `DigMontage`-`Montage` mess we had in the existing plot with `point_names` and custom transforms. (#6649, maybe different PR)

- [ ] Make a none smoke test for applied transforms https://github.com/massich/mne-python/pull/31 (I've close it by error, it still applies)

---

Log of past PRs:
* Add example showing all the eeg helmets (#6158)
* MRG: Prepare BTI to refactor for Digitization (#6228)
* MAINT: Refactor digitation for KIT, artemis123, bti (#6368)
* ENH: Add digitization class (#6369)
* MNT: Change DigMontage representation to use Digitization (#6639)
* Make mne/digitization private mne/_digitization (#6700)

Cross-reference issues:

* https://github.com/mne-tools/mne-python/issues/3893#issuecomment-271925975
* #6698

---

Here is a summary of the readers with respect to how they are tested. Main focus: does the reader go through `_test_raw_reader`? has the reader been tested with `digitization` or `None`? Does the reader have digitization or a `montage`?

```sh
                       | _test_raw_reader | None | Digitization | other   |
-----------------------+------------------+------+--------------+---------+
RawArray               |     x            |  x   |              |         |
read_raw_artemis123    |     x            |      |     x        |         |   
read_raw_bdf           |                  |      |              | montage |
read_raw_brainvision   |     x            |  x   |     x        |         |    
read_raw_bti           |     x            |  x   |     x        |         |
read_raw_cnt           |     x            |  x   |              | montage |
read_raw_ctf           |     x            |      |     x        |         |
read_raw_edf           |     x            |  x   |     x        |         |
read_raw_eeglab        |     x            |      |     x        |         |
read_raw_egi           |     x            |  x   |              | montage |
read_raw_eximia        |     x            |  x   |              | ------- |
read_raw_fieldtrip     |                  |      |              | ------- |
read_raw_fif           |     x            |      |     x        |         |
read_raw_gdf           |     x            |  x   |              | montage |
read_raw_kit           |     x            |  x   |     x        |         |
read_raw_nicolet       |     x            |  x   |              | montage |
```

---

other notes:
1) duplicated montages
```py
import os.path as op
import mne
fname = op.join(op.dirname(mne.io.edf.__file__), 'tests', 'data', 'biosemi.hpts')

default_biosemi64 = mne.channels.read_montage('biosemi64')
edf_testing_biosemi64 = mne.channels.read_montage(fname)
```

**Comment by GuillaumeFavelier** [comment]
Thanks for the overview @massich! I think there is also #6412 (add a `plot()` function to the `Digitization` class). I still have to integrate @agramfort reviews.

**Comment by massich** [comment]
@GuillaumeFavelier right!

**Comment by larsoner** [comment]
@massich updated top description with my suggested order / description based on extrapolating what I discussed with @agramfort

**Comment by massich** [comment]
just to make sure that we are all on the same page. This should pass without warning error nothing:

```py
def test_montage():
    raw_montage = read_raw_*(fname, montage=my_montage)
    raw_none = read_raw_*(fname, montage=None)
    raw_none.set_montage(montage)
    assert object_diff(raw_none.info['chs'], raw_montage.info['chs'])
    assert object_diff(raw_none.info['dig'], raw_montage.info['dig'])
```

**Comment by agramfort** [comment]
yes exactly

>

**Comment by larsoner** [comment]
Yes in this PR. Eventually in this release cycle we will deprecade the `read_raw_*(fname, montage=my_montage)`, but not in this PR. (It should be almost trivial after this PR.)

**Comment by larsoner** [comment]
Sorry, I meant to say that yes, that should be the behavior in #6462.

In the PR after that, `read_raw_*(fname, montage=my_montage)` should be deprecated and the user told to do `raw.set_montage(my_montage)`.

**Comment by massich** [comment]
`update_ch_names` has been exposed in 0.19. Once Digitization is here, we should be able to remove it from the signature. 
https://github.com/mne-tools/mne-python/blob/2f9873e7759e62f8471326e37a2ad1cdd2c2e65d/mne/channels/channels.py#L446

In other words, `Digitization` should go in before releasing so that we don't need to deprecate this parameter.

**Comment by massich** [comment]
now that montage is deprecated, the idea is that `raw.set_montage` only takes Digitization and that as a middle step montages and digmontages had to be transformed to Digitizations, am I right? @agramfort, @larsoner

**Comment by larsoner** [comment]
Yeah I think so.

**Comment by agramfort** [comment]
question is should we still call it set_montage or we introduce a new
method set_digitization?
just thinking out loud...

**Comment by massich** [comment]
`set_montage` sounds fine to me

**Comment by massich** [comment]
There are at least two ways of getting the digitization information from a fif file:

https://github.com/mne-tools/mne-python/blob/897c3b2d12d0562f888784c5e18c2da31ed27ceb/mne/io/meas_info.py#L891

https://github.com/mne-tools/mne-python/blob/897c3b2d12d0562f888784c5e18c2da31ed27ceb/mne/channels/montage.py#L637

**Comment by agramfort** [comment]
not really as the anything is done after _read_dig_fif(fid, tree) is
just to make a DigMontage from a dig (get numpy arrays and a few attributes)

>

**Comment by massich** [comment]
I think that we could simplify mne/viz/montage.py quite a lot. see #6649

**Comment by massich** [comment]
cross-reference https://github.com/mne-tools/mne-python/issues/3893#issuecomment-271925975 and #6461

**Comment by massich** [comment]
Regarding the `kind` we have this `FIF.FIFV_MNE_COORD_DIGITIZER` and `FIFFV_COORD_ISOTRAK` that is used nowhere.

```sh
~/code/mne-python read_dig_montage_polhemus
(mne) ❯ git grep -i 'FIFFV_MNE_COORD_DIGITIZER'
mne/io/constants.py:FIFF.FIFFV_MNE_COORD_DIGITIZER   = FIFF.FIFFV_COORD_ISOTRAK # Original (Polhemus) digitizer coordinates
mne/io/tests/test_constants.py:    FIFFV_MNE_COORD_DIGITIZER='FIFFV_COORD_ISOTRAK',
```

**Comment by agramfort** [comment]
yes then we need to change the read_dig_xxx so they don't use unknown but
the proper
source of the data. We would need to add a constant for captrack though

**Comment by larsoner** [comment]
@massich do we need any of the rest of these for 0.19? Or just #6764?

**Comment by massich** [comment]
I think #6764 is enough. I'm closing this one
